### ISSUE TITLE
Running on local machine?

### ISSUE THREAD

**Issue by McbainDist** [gfwilliams/ThinGallery#12]
Hi there,

Great work by the way.  This is perfect for a little project I am working on.  I've created a simple HTML "Dashboard" for multiple local selling sites and one section is a directory to all the images I have (a local folder).  I think I am running into an issue since all my files are local on my computer, even the dashboard.html

Is there a way around this or will I have to have this running on a web server?

**Comment by gfwilliams** [comment]
I think you need it to be running on a web server, but that web server can be local.

Basically the gallery needs to be able to access an 'index page' (eg. http://www.espruino.com/press/) that shows all the files that are in the folder - otherwise it has no way of knowing what to display.

If I run the gallery as a file I get the following error:

```
gallery.html:444 Access to XMLHttpRequest at 'file:///home/gw/workspace/ThinGallery/' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
```

Basically the browser's just not willing to let the gallery access files on your disk drive. Makes sense really as otherwise a malicious webpage that got saved locally could access all the files on your disk.
