### ISSUE TITLE
How to sort images by date descending?

### ISSUE THREAD

**Issue by km4lin** [gfwilliams/ThinGallery#7]
Hi,
is there option to sort images by name descending?
for example I have images like:
2018-08-08_21-35-36_636.jpg
2018-08-08_21-43-33_369.jpg
2018-08-08_21-43-53_525.jpg

**Comment by gfwilliams** [comment]
Since it works off the standard directory listing from the web server, if you view the directory as-is you should get a heading like this:

![image](https://user-images.githubusercontent.com/754445/43887234-111eed24-9bb6-11e8-8420-aa40e7e49fe9.png)

If you click on one of those headings you should be able to sort in a certain way. If you take that bit of the URL and add it to the gallery's URL you should get the sort you want.

eg.

Normal URL: http://www.espruino.com/press/gallery.html?pixljs
Sorted by name, ascending: http://www.espruino.com/press/gallery.html?pixljs/?C=N;O=A

If you needed that on every view you could just edit the code so that it was added to every page. Eg here:

https://github.com/gfwilliams/ThinGallery/blob/master/gallery.html#L386

change `xhr.open("GET", baseURL);` to `xhr.open("GET", baseURL+"?C=N;O=A");`

**Comment by km4lin** [comment]
Thank you!
